
WIDTH = 837
HEIGHT = 304

ORIGIN = (0,0)
FPS = 40 
SPEED_C = 5
SPEED_B = 5

SIZE_SCREEN = (WIDTH, HEIGHT)
SIZE_ICON = (36,30)
SIZE_LIFE = (45,39)
SIZE_CAT = (38, 44)

DISPLAY_BOTTOM = HEIGHT
DISPLAY_TOP = 0
DISPLAY_RIGHT = WIDTH
DISPLAY_LEFT = 0
DISPLAY_CENTER_X = WIDTH // 2
DISPLAY_CENTER_Y = HEIGHT // 2
DISPLAY_MIDTOP = (DISPLAY_CENTER_X,0)

FPS = 60